apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rest-client-resteasy-microprofile
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rest-client-resteasy-microprofile
    app.kubernetes.io/part-of: resteasy-microprofile
  name: rest-client-resteasy-microprofile
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: rest-client-resteasy-microprofile
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: rest-client-resteasy-microprofile
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-rnovelli-tenant/resteasy-microprofile/rest-client-resteasy-microprofile@sha256:a6a7356fdc51d773a8392d70e7bec7549b1fd056ee7e1f874eca4cf80f40821a
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
