apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: config-resteasy-microprofile
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: config-resteasy-microprofile
    app.kubernetes.io/part-of: resteasy-microprofile
  name: config-resteasy-microprofile
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: config-resteasy-microprofile
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: config-resteasy-microprofile
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-rnovelli-tenant/resteasy-microprofile/config-resteasy-microprofile@sha256:867cb78169cb16fe0f2204c3a7aa178daf1abb7c81efc87a639b06259417536e
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
