apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: config-resteasy-microprofile
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: config-resteasy-microprofile
    app.kubernetes.io/part-of: resteasy-microprofile
  name: config-resteasy-microprofile
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-quarkus-app
    app.kubernetes.io/instance: config-resteasy-microprofile
status:
  loadBalancer: {}
