apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: context-propagation-resteasy-microprofile
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: context-propagation-resteasy-microprofile
    app.kubernetes.io/part-of: resteasy-microprofile
  name: context-propagation-resteasy-microprofile
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: context-propagation-resteasy-microprofile
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: context-propagation-resteasy-microprofile
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-rnovelli-tenant/resteasy-microprofile/context-propagation-resteasy-microprofile@sha256:4a42bf1f38e98904ed16ace49c28c2ee7996d7f765dd72880895c75f262d5752
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
